using System;
class ScriptureList
{
    private List<Scripture> bookOfMormomScriptures;
    private List<Scripture> newTestamentScriptures;
    private List<Scripture> oldTestamentScriptures;
    private List<Scripture> doctrineAndCovenantsScriptures;

    public ScriptureList()
    {
        bookOfMormomScriptures = new List<Scripture>()
        {
            new Scripture("1 Nephi", 3, 7, 7, "And it came to pass that I, Nephi, said unto my father: I will go and do the things which the Lord hath commanded, for I know that the Lord giveth no commandments unto the children of men, save he shall prepare a way for them that they may accomplish the thing which he commandeth them."),
            new Scripture("2 Nephi", 2, 25, 25, "Adam fell that men might be; and men are, that they might have joy."),
            new Scripture("2 Nephi", 2, 27, 27, "Wherefore, men are free according to the flesh; and all things are given them which are expedient unto man. And they are free to choose liberty and eternal life, through the great Mediator of all men, or to choose captivity and death, according to the captivity and power of the devil; for he seeketh that all men might be miserable like unto himself."),
            new Scripture("2 Nephi", 26, 33, 33, "For none of these iniquities come of the Lord; for he doeth that which is good among the children of men; and he doeth nothing save it be plain unto the children of men; and he inviteth them all to come unto him and partake of his goodness; and he denieth none that come unto him, black and white, bond and free, male and female; and he remembereth the heathen; and all are alike unto God, both Jew and Gentile."),
            new Scripture("2 Nephi", 28, 30, 30, "For behold, thus saith the Lord God: I will give unto the children of men line upon line, precept upon precept, here a little and there a little; and blessed are those who hearken unto my precepts, and lend an ear unto my counsel, for they shall learn wisdom; for unto him that receiveth I will give more; and from them that shall say, We have enough, from them shall be taken away even that which they have."),
            new Scripture("2 Nephi", 32, 3, 3, "Angels speak by the power of the Holy Ghost; wherefore, they speak the words of Christ. Wherefore, I said unto you, feast upon the words of Christ; for behold, the words of Christ will tell you all things what ye should do."),
            new Scripture("2 Nephi", 32, 8, 9, "And now, my beloved brethren, I perceive that ye ponder still in your hearts; and it grieveth me that I must speak concerning this thing. For if ye would hearken unto the Spirit which teacheth a man to pray, ye would know that ye must pray; for the evil spirit teacheth not a man to pray, but teacheth him that he must not pray.\nBut behold, I say unto you that ye must pray always, and not faint; that ye must not perform any thing unto the Lord save in the first place ye shall pray unto the Father in the name of Christ, that he will consecrate thy performance unto thee, that thy performance may be for the welfare of thy soul."),
            new Scripture("Mosiah", 2, 17, 17, "And behold, I tell you these things that ye may learn wisdom; that ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God."),
            new Scripture("Mosiah", 2, 41, 41, "And moreover, I would desire that ye should consider on the blessed and happy state of those that keep the commandments of God. For behold, they are blessed in all things, both temporal and spiritual; and if they hold out faithful to the end they are received into heaven, that thereby they may dwell with God in a state of never-ending happiness. O remember, remember that these things are true; for the Lord God hath spoken it."),
            new Scripture("Mosiah", 3, 19, 19, "For the natural man is an enemy to God, and has been from the fall of Adam, and will be, forever and ever, unless he yields to the enticings of the Holy Spirit, and putteth off the natural man and becometh a saint through the atonement of Christ the Lord, and becometh as a child, submissive, meek, humble, patient, full of love, willing to submit to all things which the Lord seeth fit to inflict upon him, even as a child doth submit to his father."),
            new Scripture("Mosiah", 4, 9, 9, "Believe in God; believe that he is, and that he created all things, both in heaven and in earth; believe that he has all wisdom, and all power, both in heaven and in earth; believe that man doth not comprehend all the things which the Lord can comprehend."),
            new Scripture("Mosiah", 18, 8, 10, "And it came to pass that he said unto them: Behold, here are the waters of Mormon (for thus were they called) and now, as ye are desirous to come into the fold of God, and to be called his people, and are willing to bear one another’s burdens, that they may be light;\nYea, and are willing to mourn with those that mourn; yea, and comfort those that stand in need of comfort, and to stand as witnesses of God at all times and in all things, and in all places that ye may be in, even until death, that ye may be redeemed of God, and be numbered with those of the first resurrection, that ye may have eternal life—\nNow I say unto you, if this be the desire of your hearts, what have you against being baptized in the name of the Lord, as a witness before him that ye have entered into a covenant with him, that ye will serve him and keep his commandments, that he may pour out his Spirit more abundantly upon you?"),
            new Scripture("Alma", 7, 11, 13, "And he shall go forth, suffering pains and afflictions and temptations of every kind; and this that the word might be fulfilled which saith he will take upon him the pains and the sicknesses of his people.\nAnd he will take upon him death, that he may loose the bands of death which bind his people; and he will take upon him their infirmities, that his bowels may be filled with mercy, according to the flesh, that he may know according to the flesh how to succor his people according to their infirmities.\nNow the Spirit knoweth all things; nevertheless the Son of God suffereth according to the flesh that he might take upon him the sins of his people, that he might blot out their transgressions according to the power of his deliverance; and now behold, this is the testimony which is in me."),
            new Scripture("Alma", 34, 9, 10, "For it is expedient that an atonement should be made; for according to the great plan of the Eternal God there must be an atonement made, or else all mankind must unavoidably perish; yea, all are hardened; yea, all are fallen and are lost, and must perish except it be through the atonement which it is expedient should be made. For it is expedient that there should be a great and last sacrifice; and then shall there be, or it must needs be, a stop to the shedding of blood; then shall the law be fulfilled; yea, it shall be all fulfilled, every jot and tittle, and none shall have passed away."),
            new Scripture("Alma", 39, 9, 9, "Now my son, I would that ye should repent and forsake your sins, and go no more after the lusts of your eyes, but cross yourself in all these things; for except ye do this ye can in nowise inherit the kingdom of God. Oh, remember, and take it upon you, and cross yourself in these things."),
            new Scripture("Alma", 41, 10, 10, "Do not suppose, because it has been spoken concerning restoration, that ye shall be restored from sin to happiness. Behold, I say unto you, wickedness never was happiness."),
            new Scripture("Helaman", 5, 12, 12, "And now, my sons, remember, remember that it is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation; that when the devil shall send forth his mighty winds, yea, his shafts in the whirlwind, yea, when all his hail and his mighty storm shall beat upon you, it shall have no power over you to drag you down to the gulf of misery and endless wo, because of the rock upon which ye are built, which is a sure foundation, a foundation whereon if men build they cannot fall."),
            new Scripture("3 Nephi", 11, 10, 11, "Behold, I am Jesus Christ, whom the prophets testified shall come into the world. And behold, I am the light and the life of the world; and I have drunk out of that bitter cup which the Father hath given me, and have glorified the Father in taking upon me the sins of the world, in the which I have suffered the will of the Father in all things from the beginning."),
            new Scripture("3 Nephi", 12, 48, 48, "Therefore I would that ye should be perfect even as I, or your Father who is in heaven is perfect."),
            new Scripture("3 Nephi", 27, 20, 20, "Now this is the commandment: Repent, all ye ends of the earth, and come unto me and be baptized in my name, that ye may be sanctified by the reception of the Holy Ghost, that ye may stand spotless before me at the last day."),
            new Scripture("Ether", 12, 6, 6, "And now, I, Moroni, would speak somewhat concerning these things; I would show unto the world that faith is things which are hoped for and not seen; wherefore, dispute not because ye see not, for ye receive no witness until after the trial of your faith."),
            new Scripture("Ether", 12, 27, 27, "And if men come unto me I will show unto them their weakness. I give unto men weakness that they may be humble; and my grace is sufficient for all men that humble themselves before me; for if they humble themselves before me, and have faith in me, then will I make weak things become strong unto them."),
            new Scripture("Moroni", 7, 45, 48, "And charity suffereth long, and is kind, and envieth not, and is not puffed up, seeketh not her own, is not easily provoked, thinketh no evil, and rejoiceth not in iniquity but rejoiceth in the truth, beareth all things, believeth all things, hopeth all things, endureth all things. Wherefore, my beloved brethren, if ye have not charity, ye are nothing, for charity never faileth. Wherefore, cleave unto charity, which is the greatest of all, for all things must fail— But charity is the pure love of Christ, and it endureth forever; and whoso is found possessed of it at the last day, it shall be well with him. Wherefore, my beloved brethren, pray unto the Father with all the energy of heart, that ye may be filled with this love, which he hath bestowed upon all who are true followers of his Son, Jesus Christ; that ye may become the sons of God; that when he shall appear we shall be like him, for we shall see him as he is; that we may have this hope; that we may be purified even as he is pure. Amen."),
            new Scripture("Moroni", 10, 4, 5, "And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true; and if ye shall ask with a sincere heart, with real intent, having faith in Christ, he will manifest the truth of it unto you, by the power of the Holy Ghost. And by the power of the Holy Ghost ye may know the truth of all things."),

        };

        newTestamentScriptures = new List<Scripture>()
        {
            new Scripture("Matthew", 5, 14, 16, "Ye are the light of the world. A city that is set on a hill cannot be hid. Neither do men light a candle, and put it under a bushel, but on a candlestick, and it giveth light unto all that are in the house. Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."),
            new Scripture("Matthew", 11, 28, 30, "Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light."),
            new Scripture("Matthew", 16, 15, 19, "He saith unto them, But whom say ye that I am? And Simon Peter answered and said, Thou art the Christ, the Son of the living God. And Jesus answered and said unto him, Blessed art thou, Simon Barjona: for flesh and blood hath not revealed it unto thee, but my Father which is in heaven. And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it. And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven."),
            new Scripture("Matthew", 22, 36, 39, "Master, which is the great commandment in the law? Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself."),
            new Scripture("Luke", 2, 10, 12, "And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people. For unto you is born this day in the city of David a Saviour, which is Christ the Lord. And this shall be a sign unto you; Ye shall find the babe wrapped in swaddling clothes, lying in a manger."),
            new Scripture("Luke", 22, 19, 20, "And he took bread, and gave thanks, and brake it, and gave unto them, saying, This is my body which is given for you: this do in remembrance of me. Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you."),
            new Scripture("Luke", 24, 36, 39, "And as they thus spake, Jesus himself stood in the midst of them, and saith unto them, Peace be unto you. But they were terrified and affrighted, and supposed that they had seen a spirit. And he said unto them, Why are ye troubled? and why do thoughts arise in your hearts? Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have."),
            new Scripture("John", 3, 5, 5, "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God."),
            new Scripture("John", 3, 16, 16, "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."),
            new Scripture("John", 7, 17, 17, "If any man will do his will, he shall know of the doctrine, whether it be of God, or whether I speak of myself."),
            new Scripture("John", 17, 3, 3, "And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent."),
            new Scripture("1 Corinthians", 6, 19, 20, "What? know ye not that your body is the temple of the Holy Ghost which is in you, which ye have of God, and ye are not your own? For ye are bought with a price: therefore glorify God in your body, and in your spirit, which are God's."),
            new Scripture("1 Corinthians", 11, 11, 11, "Nevertheless neither is the man without the woman, neither the woman without the man, in the Lord."),
            new Scripture("1 Corinthians", 15, 20, 22, "But now is Christ risen from the dead, and become the firstfruits of them that slept. For since by man came death, by man came also the resurrection of the dead. For as in Adam all die, even so in Christ shall all be made alive."),
            new Scripture("1 Corinthians", 15, 40, 42, "There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another. There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory. So also is the resurrection of the dead. It is sown in corruption; it is raised in incorruption."),
            new Scripture("Ephesians", 1, 10, 10, "That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; even in him."),
            new Scripture("Ephesians", 2, 19, 20, "Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God; And are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone."),
            new Scripture("2 Thessalonians", 2, 1, 3, "Now we beseech you, brethren, by the coming of our Lord Jesus Christ, and by our gathering together unto him, That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand. Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition."),
            new Scripture("2 Timothy", 3, 15, 17, "And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus. All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, throughly furnished unto all good works."),
            new Scripture("Hebrews", 12, 9, 9, "Furthermore we have had fathers of our flesh which corrected us, and we gave them reverence: shall we not much rather be in subjection unto the Father of spirits, and live?"),
            new Scripture("James", 1, 5, 6, "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him. But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed."),
            new Scripture("James", 2, 17, 18, "Even so faith, if it hath not works, is dead, being alone. Yea, a man may say, Thou hast faith, and I have works: shew me thy faith without thy works, and I will shew thee my faith by my works."),
            new Scripture("1 Peter", 4, 6, 6, "For for this cause was the gospel preached also to them that are dead, that they might be judged according to men in the flesh, but live according to God in the spirit."),
            new Scripture("Revelation", 20, 12, 12, "And I saw the dead, small and great, stand before God; and the books were opened: and another book was opened, which is the book of life: and the dead were judged out of those things which were written in the books, according to their works."),
        };

        oldTestamentScriptures = new List<Scripture>()
        {
            new Scripture("Genesis", 1, 26, 27, "Then God said, 'Let us make mankind in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.' So God created mankind in his own image, in the image of God he created them; male and female he created them."),
            new Scripture("Genesis", 2, 24, 24, "That is why a man leaves his father and mother and is united to his wife, and they become one flesh."),
            new Scripture("Genesis", 39, 9, 9, "No one is greater in this house than I am. My master has withheld nothing from me except you, because you are his wife. How then could I do such a wicked thing and sin against God?"),
            new Scripture("Exodus", 20, 3, 17, "You shall have no other gods before me. You shall not make for yourselves an image in the form of anything in heaven above or on the earth below or in the waters beneath the earth. You shall not misuse the name of the Lord your God. Remember the Sabbath day by keeping it holy. Honor your father and your mother. You shall not murder. You shall not commit adultery. You shall not steal. You shall not give false testimony against your neighbor. You shall not covet your neighbor's house. You shall not covet your neighbor's wife, or his male or female servant, his ox or donkey, or anything that belongs to your neighbor."),
            new Scripture("Joshua", 24, 15, 15, "But if serving the Lord seems undesirable to you, then choose for yourselves this day whom you will serve... But as for me and my household, we will serve the Lord."),
            new Scripture("Psalm", 24, 3, 4, "Who may ascend the mountain of the Lord? Who may stand in his holy place? The one who has clean hands and a pure heart, who does not trust in an idol or swear by a false god."),
            new Scripture("Proverbs", 3, 5, 6, "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight."),
            new Scripture("Isaiah", 1, 18, 18, "'Come now, let us settle the matter,' says the Lord. 'Though your sins are like scarlet, they shall be as white as snow; though they are red as crimson, they shall be like wool.'"),
            new Scripture("Isaiah", 5, 20, 20, "Woe to those who call evil good and good evil, who put darkness for light and light for darkness, who put bitter for sweet and sweet for bitter."),
            new Scripture("Isaiah", 29, 13, 14, "The Lord says: 'These people come near to me with their mouth and honor me with their lips, but their hearts are far from me. Their worship of me is based on merely human rules they have been taught. Therefore once more I will astound these people with wonder upon wonder; the wisdom of the wise will perish, the intelligence of the intelligent will vanish.'"),
            new Scripture("Isaiah", 53, 3, 5, "He was despised and rejected by mankind, a man of suffering, and familiar with pain. Like one from whom people hide their faces he was despised, and we held him in low esteem. Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted. But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed."),
            new Scripture("Isaiah", 58, 6, 7, "Is not this the kind of fasting I have chosen: to loose the chains of injustice and untie the cords of the yoke, to set the oppressed free and break every yoke? Is it not to share your food with the hungry and to provide the poor wanderer with shelter—when you see the naked, to clothe them, and not to turn away from your own flesh and blood?"),
            new Scripture("Isaiah", 58, 13, 14, "'If you keep your feet from breaking the Sabbath and from doing as you please on my holy day, if you call the Sabbath a delight and the Lord's holy day honorable, and if you honor it by not going your own way and not doing as you please or speaking idle words, then you will find your joy in the Lord, and I will cause you to ride in triumph on the heights of the land and to feast on the inheritance of your father Jacob.' For the mouth of the Lord has spoken."),
            new Scripture("Jeremiah", 1, 4, 5, "The word of the Lord came to me, saying, 'Before I formed you in the womb I knew you, before you were born I set you apart; I appointed you as a prophet to the nations.'"),
            new Scripture("Ezekiel", 3, 16, 17, "At the end of seven days the word of the Lord came to me: 'Son of man, I have made you a watchman for the people of Israel; so hear the word I speak and give them warning from me.'"),
            new Scripture("Ezekiel", 37, 15, 17, "The word of the Lord came to me: 'Son of man, take a stick of wood and write on it, 'Belonging to Judah and the Israelites associated with him.' Then take another stick of wood and write on it, 'Belonging to Joseph (that is, to Ephraim) and all the Israelites associated with him.' Join them together into one stick so that they will become one in your hand.'"),
            new Scripture("Daniel", 2, 44, 45, "'In the time of those kings, the God of heaven will set up a kingdom that will never be destroyed, nor will it be left to another people. It will crush all those kingdoms and bring them to an end, but it will itself endure forever.'"),
            new Scripture("Amos", 3, 7, 7, "Surely the Sovereign Lord does nothing without revealing his plan to his servants the prophets."),
            new Scripture("Malachi", 3, 8, 10, "'Will a mere mortal rob God? Yet you rob me. But you ask, 'How are we robbing you?' 'In tithes and offerings. You are under a curse—your whole nation—because you are robbing me. Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this,' says the Lord Almighty, 'and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it.'"),
            new Scripture("Malachi", 4, 5, 6, "'See, I will send the prophet Elijah to you before that great and dreadful day of the Lord comes. He will turn the hearts of the parents to their children, and the hearts of the children to their parents; or else I will come and strike the land with total destruction.'")

        };

        doctrineAndCovenantsScriptures = new List<Scripture>()
        {
            new Scripture("Joseph Smith—History", 1, 15, 20, "While I was thus employed, I discovered a light, appearing in the midst of the brightness of the glory of the Lord, and, as it were, the brightness of the sun; and, as I looked, I beheld two Personages, whose brightness and glory defy all description, standing above me in the air. One of them spake unto me, calling me by name and said, pointing to the other—This is my Beloved Son. Hear him!"),
            new Scripture("Doctrine and Covenants", 1, 30, 30, "The only true and living church upon the face of the whole earth, which I, the Lord, am well pleased, speaking unto the church collectively and not individually."),
            new Scripture("Doctrine and Covenants", 1, 37, 38, "And this I do, that I may prove to the world that I am the same yesterday, today, and forever. And that I speak unto the world, and will continue to speak unto the world, until the end thereof. And the voice of the Lord shall be unto all nations, and unto all peoples, that they may know of my will."),
            new Scripture("Doctrine and Covenants", 6, 36, 36, "Look unto me in every thought; doubt not, fear not."),
            new Scripture("Doctrine and Covenants", 8, 2, 3, "Yea, behold, I will tell you in your mind and in your heart, by the Holy Ghost, which shall come upon you and which shall dwell in your heart."),
            new Scripture("Doctrine and Covenants", 13, 1, 1, "Upon you, my fellow servants, I confer the Priesthood of Aaron, which holds the keys of the ministering of angels, and of the gospel of repentance, and of baptism by immersion for the remission of sins; and this shall never be taken again from the earth, until the sons of Levi do offer again an offering unto the Lord in righteousness."),
            new Scripture("Doctrine and Covenants", 18, 10, 11, "Remember the worth of souls is great in the sight of God; And that he that repenteth and doeth the commandments of God shall be forgiven."),
            new Scripture("Doctrine and Covenants", 18, 15, 16, "And if it so be that you should bring many souls unto me, how great will be your joy with them in the kingdom of my Father! And now, if your joy will be great with one soul that you have brought unto me into the kingdom of my Father, how great will be your joy if you should bring many souls unto me!"),
            new Scripture("Doctrine and Covenants", 19, 16, 19, "For behold, I, God, have suffered these things for all, that they might not suffer if they would repent; But if they would not repent they must suffer even as I did; which suffering caused myself, even God, the greatest of all, to tremble because of pain, and to bleed at every pore, and to suffer both body and spirit—and would that I might not drink the bitter cup, and shrink."),
            new Scripture("Doctrine and Covenants", 21, 4, 6, "Wherefore, meaning the church, ye shall receive the prophet's word as if from mine own mouth, in all patience and faith. For by doing these things the church shall be built up, and the kingdom of God shall be established upon the earth, to the overthrow of all other kingdoms, and to the blessing and salvation of the world."),
            new Scripture("Doctrine and Covenants", 29, 10, 11, "And it shall be a sign unto the world, that I will reveal myself from heaven with power and great glory, with all the holy angels; and they shall fall down, and worship me, and shall come forth and live with me in the great and last day of my kingdom, which I will establish in righteousness."),
            new Scripture("Doctrine and Covenants", 49, 15, 17, "Marriage is ordained of God. The first commandment which I gave unto man was that he should love and cleave unto his wife, and cleave unto her, as she cleaves unto him, that they might become one in flesh, and that they might have joy and be blessed in the institution of marriage."),
            new Scripture("Doctrine and Covenants", 58, 42, 43, "He who has repented of his sins, the same is forgiven, and I, the Lord, remember them no more. By this ye may know that I forgive the sins of the repentant, for the sins of the sinner who repenteth are forgiven."),
            new Scripture("Doctrine and Covenants", 64, 9, 11, "Wherefore, I say unto you, that ye shall forgive all men, and that ye shall forgive all men their trespasses, and that ye shall forgive them as I forgive you."),
            new Scripture("Doctrine and Covenants", 76, 22, 24, "And now the Lord said unto me, I have created the worlds, and they are mine, and I have sent them forth and appointed them to fulfill the purposes of the eternities. And the Lord hath sent forth his Spirit into all the world, that his works may be accomplished, and his name glorified."),
            new Scripture("Doctrine and Covenants", 82, 10, 10, "I, the Lord, am bound when ye do what I say, but when ye do not what I say, ye have no promise."),
            new Scripture("Doctrine and Covenants", 84, 20, 22, "Therefore, in the ordinances thereof, the power of godliness is manifest. And without the ordinances thereof, the power of godliness is not manifest."),
            new Scripture("Doctrine and Covenants", 88, 118, 118, "And as all have not faith, all do not have the knowledge of God, nor the understanding of His will. Therefore, seek learning, even by study and also by faith, and by all that ye shall be able to understand the will of the Lord."),
            new Scripture("Doctrine and Covenants", 89, 18, 21, "And all saints who remember to keep and do these things, walking in obedience to the commandments of the Lord, shall have the blessings of health and strength, and the blessings of the Word of Wisdom."),
            new Scripture("Doctrine and Covenants", 107, 8, 8, "The Melchizedek Priesthood has power and authority to administer in spiritual things, and to bind and loose the powers of the heavens and the earth."),
            new Scripture("Doctrine and Covenants", 121, 36, 42, "The rights of the priesthood are inseparably connected with the powers of heaven, and cannot be controlled nor handled except upon the principles of righteousness."),
            new Scripture("Doctrine and Covenants", 130, 22, 23, "The Father has a body of flesh and bones as tangible as man's; the Son also; but the Holy Ghost has not a body of flesh and bones, but is a personage of Spirit. Were it not so, the Holy Ghost could not dwell in us."),
            new Scripture("Doctrine and Covenants", 131, 1, 4, "In the new and everlasting covenant of marriage, if a man marry a woman in the temple and they enter into the new and everlasting covenant, they shall be sealed together, and they shall inherit the glory of the highest kingdom of heaven."),
            new Scripture("Doctrine and Covenants", 135, 3, 3, "Joseph Smith, the prophet and seer of the Lord, has done more, save Jesus only, for the salvation of men in this world, than any other man that ever lived in it.")

        };
    }

    public List<Scripture> GetOldTestamentScriptures()
    {
        return oldTestamentScriptures;
    }

    public List<Scripture> GetNewTestamentScriptures()
    {
        return newTestamentScriptures;
    }

    public List<Scripture> GetBookOfMormonScriptures()
    {
        return bookOfMormomScriptures;
    }

    public List<Scripture> GetDoctrineAndCovenantsScriptures()
    {
        return doctrineAndCovenantsScriptures;
    }
}